---
services:
  unifi-os-server:
# use this if cooking container locally
    image: unifi-os-server:latest
# use this if using container from published source
#    image: ghcr.io/lemker/unifi-os-server:latest
    build: .
    container_name: unifi-os-server
    cap_add:
      - NET_RAW
      - NET_ADMIN
    tmpfs:
      - /run:exec
      - /run/lock
      - /tmp:exec
      - /var/lib/journal
      - /var/opt/unifi/tmp:size=64m
    env_file: .env
    volumes:
      - ${VOLUME_PREFIX}/persistent:/persistent
      - ${VOLUME_PREFIX}/var-log:/var/log
      - ${VOLUME_PREFIX}/data:/data
      - ${VOLUME_PREFIX}/srv:/srv
      - ${VOLUME_PREFIX}/var-lib-unifi:/var/lib/unifi
      - ${VOLUME_PREFIX}/var-lib-mongodb:/var/lib/mongodb
      - ${VOLUME_PREFIX}/etc-rabbitmq-ssl:/etc/rabbitmq/ssl
    ports:
      - 11443:443
      - 5005:5005
      - 9543:9543
      - 6789:6789
      - 8080:8080
      - 8444:8444
      - 3478:3478/udp
      - 5514:5514/udp
      - 10003:10003/udp
      - 127.0.0.1:11084:11084
      - 5671:5671
      - 8880:8880
      - 8881:8881
      - 8882:8882
    restart: unless-stopped
