apiVersion: apps/v1
kind: Deployment
metadata:
  name: uosserver
  namespace: unifi
  labels:
    app: uosserver
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: uosserver
  template:
    metadata:
      labels:
        app: uosserver
    spec:
      containers:
      - name: uosserver
        image: ghcr.io/lemker/uosserver:0.0.49
        env:
        - name: UOS_UUID
          value: ""
        - name: UOS_SERVER_VERSION
          value: "4.3.5"
        - name: FIRMWARE_PLATFORM
          value: "linux-x64"
        securityContext:
          privileged: true
        volumeMounts:
        - name: uosserver-persistent
          mountPath: /persistent
        - name: uosserver-var-log
          mountPath: /var/log
        - name: uosserver-data
          mountPath: /data
        - name: uosserver-srv
          mountPath: /srv
        - name: uosserver-var-lib-unifi
          mountPath: /var/lib/unifi
        - name: uosserver-var-lib-mongodb
          mountPath: /var/lib/mongodb
        - name: uosserver-etc-rabbitmq-ssl
          mountPath: /etc/rabbitmq/ssl
        livenessProbe:
          httpGet:
            path: /api/ping
            port: 80
          initialDelaySeconds: 10          
          periodSeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: uosserver-persistent
        persistentVolumeClaim:
          claimName: uosserver-persistent
      - name: uosserver-var-log
        persistentVolumeClaim:
          claimName: uosserver-var-log
      - name: uosserver-data
        persistentVolumeClaim:
          claimName: uosserver-data
      - name: uosserver-srv
        persistentVolumeClaim:
          claimName: uosserver-srv
      - name: uosserver-var-lib-unifi
        persistentVolumeClaim:
          claimName: uosserver-var-lib-unifi
      - name: uosserver-var-lib-mongodb
        persistentVolumeClaim:
          claimName: uosserver-var-lib-mongodb
      - name: uosserver-etc-rabbitmq-ssl
        persistentVolumeClaim:
          claimName: uosserver-etc-rabbitmq-ssl

---
apiVersion: v1
kind: Service
metadata:
  name: uosserver-webui-svc
  namespace: unifi
spec:
  ports:
  - name: webui
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: uosserver

---
apiVersion: v1
kind: Service
metadata:
  name: uosserver-rtp-svc
  namespace: unifi
spec:
  ports:
  - name: rtp
    port: 5005
    protocol: TCP
    targetPort: 5005
  selector:
    app: uosserver

---
apiVersion: v1
kind: Service
metadata:
  name: uosserver-id-hub-svc
  namespace: unifi
spec:
  ports:
  - name: id-hub
    port: 9543
    protocol: TCP
    targetPort: 9543
  selector:
    app: uosserver

---
apiVersion: v1
kind: Service
metadata:
  name: uosserver-mobile-speedtest-svc
  namespace: unifi
spec:
  ports:
  - name: mobile-speedtest
    port: 6789
    protocol: TCP
    targetPort: 6789
  selector:
    app: uosserver

---
apiVersion: v1
kind: Service
metadata:
  name: uosserver-communication-svc
  namespace: unifi
spec:
  ports:
  - name: communication
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: uosserver

---
apiVersion: v1
kind: Service
metadata:
  name: uosserver-network-app-svc
  namespace: unifi
spec:
  ports:
  - name: network-app
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: uosserver

---
apiVersion: v1
kind: Service
metadata:
  name: uosserver-hotspot-secured-svc
  namespace: unifi
spec:
  ports:
  - name: hotspot-secured
    port: 8444
    protocol: TCP
    targetPort: 8444
  selector:
    app: uosserver

---
apiVersion: v1
kind: Service
metadata:
  name: uosserver-stun-svc
  namespace: unifi
spec:
  ports:
  - name: stun
    port: 3478
    protocol: UDP
    targetPort: 3478
  selector:
    app: uosserver

---
apiVersion: v1
kind: Service
metadata:
  name: uosserver-syslog-svc
  namespace: unifi
spec:
  ports:
  - name: syslog
    port: 5514
    protocol: UDP
    targetPort: 5514
  selector:
    app: uosserver

---
apiVersion: v1
kind: Service
metadata:
  name: uosserver-discovery-svc
  namespace: unifi
spec:
  ports:
  - name: discovery
    port: 10003
    protocol: UDP
    targetPort: 10003
  selector:
    app: uosserver

---
apiVersion: v1
kind: Service
metadata:
  name: uosserver-site-supervisor-svc
  namespace: unifi
spec:
  ports:
  - name: site-supervisor
    port: 11084
    protocol: TCP
    targetPort: 11084
  selector:
    app: uosserver

---
apiVersion: v1
kind: Service
metadata:
  name: uosserver-aqmps-svc
  namespace: unifi
spec:
  ports:
  - name: aqmps
    port: 5671
    protocol: TCP
    targetPort: 5671
  selector:
    app: uosserver

---
apiVersion: v1
kind: Service
metadata:
  name: uosserver-hotspot-redirect-0-svc
  namespace: unifi
spec:
  ports:
  - name: hotspot-redirect-0
    port: 8880
    protocol: TCP
    targetPort: 8880
  selector:
    app: uosserver

---
apiVersion: v1
kind: Service
metadata:
  name: uosserver-hotspot-redirect-1-svc
  namespace: unifi
spec:
  ports:
  - name: hotspot-redirect-1
    port: 8881
    protocol: TCP
    targetPort: 8881
  selector:
    app: uosserver

---
apiVersion: v1
kind: Service
metadata:
  name: uosserver-hotspot-redirect-2-svc
  namespace: unifi
spec:
  ports:
  - name: hotspot-redirect-2
    port: 8882
    protocol: TCP
    targetPort: 8882
  selector:
    app: uosserver

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uosserver-ingress
  namespace: unifi
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "unifi.example.com"
    secretName: tls-secret
  rules:
  - host: unifi.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: uosserver-webui-svc
            port:
              number: 443

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uosserver-persistent
  namespace: unifi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uosserver-var-log
  namespace: unifi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uosserver-data
  namespace: unifi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uosserver-srv
  namespace: unifi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uosserver-var-lib-unifi
  namespace: unifi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uosserver-var-lib-mongodb
  namespace: unifi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uosserver-etc-rabbitmq-ssl
  namespace: unifi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
